### ISSUE TITLE
Explicit the license for this project

### ISSUE THREAD

**Issue by bzg** [alexfauquette/physic-shem#1]
I suggest using a commonly used license like the [MIT license](https://spdx.org/licenses/MIT.html).

This requires adding a `LICENSE` file like [this one](https://github.com/facebook/react/blob/master/LICENSE), adapted to your name.

This could also be mentioned in the `package.json` file.

Let me know if I can help further in any way!

**Comment by alexfauquette** [comment]
Thanks for the suggestion => 01745f621c70e81f5a4af3aaf3f63727e7cf481e

**Comment by bzg** [comment]
Thanks a lot!
